function normName(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"");}
const ABBR={"arizonacardinals":"ARI","atlantafalcons":"ATL","baltimoreravens":"BAL","buffalobills":"BUF","carolinapanthers":"CAR","chicagobears":"CHI","cincinnatibengals":"CIN","clevelandbrowns":"CLE","dallascowboys":"DAL","denverbroncos":"DEN","detroitlions":"DET","greenbaypackers":"GB","houstontexans":"HOU","indianapoliscolts":"IND","jacksonvillejaguars":"JAX","kansascitychiefs":"KC","lasvegasraiders":"LV","losangeleschargers":"LAC","losangelesrams":"LA","miamidolphins":"MIA","minnesotavikings":"MIN","newenglandpatriots":"NE","neworleanssaints":"NO","newyorkgiants":"NYG","newyorkjets":"NYJ","philadelphiaeagles":"PHI","pittsburghsteelers":"PIT","sanfrancisco49ers":"SF","seattleseahawks":"SEA","tampabaybuccaneers":"TB","tennesseetitans":"TEN","washingtoncommanders":"WAS"};
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function abbr(n){return ABBR[normName(n)]||String(n||"").toUpperCase();}
function num(v){if(v===null||v===undefined||v==="")return null;v=Number(v);return Number.isFinite(v)?v:null;}
async function oddsApi(key){
 const u=new URL("https://api.the-odds-api.com/v4/sports/americanfootball_nfl/odds/");u.searchParams.set("apiKey",key);u.searchParams.set("regions","us");u.searchParams.set("markets","spreads");u.searchParams.set("oddsFormat","american");
 const r=await fetch(u,{cache:"no-store"}),remaining=r.headers.get("x-requests-remaining");if(!r.ok)throw new Error(`The Odds API ${r.status}: ${await r.text()}`);
 const events=await r.json(),games=[];
 for(const ev of events){const home=abbr(ev.home_team),away=abbr(ev.away_team),lines=[];for(const b of ev.bookmakers||[]){const m=(b.markets||[]).find(x=>x.key==="spreads");if(!m)continue;const h=(m.outcomes||[]).find(x=>normName(x.name)===normName(ev.home_team)),a=(m.outcomes||[]).find(x=>normName(x.name)===normName(ev.away_team)),hs=num(h?.point),as=num(a?.point);if(hs===null||as===null||Math.abs(hs+as)>.26)continue;lines.push({book:b.title||b.key,homeSpread:hs,awaySpread:as});}const hs=median(lines.map(x=>x.homeSpread)),as=median(lines.map(x=>x.awaySpread)),valid=hs!==null&&as!==null&&Math.abs(hs+as)<=.26;games.push({eventID:ev.id,startTime:ev.commence_time,home,away,valid,warning:valid?"":"no valid paired spread data",method:`The Odds API median (${lines.length} books)`,bookDetail:lines.slice(0,6).map(x=>`${x.book}:${away} ${x.awaySpread>0?"+":""}${x.awaySpread}/${home} ${x.homeSpread>0?"+":""}${x.homeSpread}`).join(" | "),homeSpread:valid?hs:null,awaySpread:valid?as:null,pairedBooks:lines.length});}
 return {games,eventCount:events.length,validCount:games.filter(g=>g.valid).length,source:"The Odds API",remaining};
}
function normTeam(t){const m={LAR:"LA",WSH:"WAS",OAK:"LV",JAC:"JAX"};t=String(t||"").toUpperCase();return m[t]||t;}
function teamAbbr(t){t=t||{};return normTeam(t.abbreviation||t.names?.short||t.name||t.teamID||"");}
function spreadRecords(ev){const out={home:null,away:null};for(const o of Object.values(ev.odds||{})){if(!o)continue;const p=String(o.periodID||"").toLowerCase(),b=String(o.betTypeID||"").toLowerCase(),side=String(o.sideID||"").toLowerCase();if(p!=="game"||b!=="sp"||(side!=="home"&&side!=="away"))continue;const se=String(o.statEntityID||"").toLowerCase();if(se&&se!==side)continue;if(!out[side])out[side]=o;}return out;}
function pairs(h,a){const hb=h?.byBookmaker||{},ab=a?.byBookmaker||{},out=[];for(const book of new Set([...Object.keys(hb),...Object.keys(ab)])){const x=hb[book],y=ab[book];if(!x||!y||x.available===false||y.available===false)continue;const hs=num(x.spread),as=num(y.spread);if(hs===null||as===null||Math.abs(hs+as)>.26)continue;out.push({book,homeSpread:hs,awaySpread:as});}return out;}
async function sgo(key){const u=new URL("https://api.sportsgameodds.com/v2/events");u.searchParams.set("leagueID","NFL");u.searchParams.set("oddsAvailable","true");u.searchParams.set("started","false");u.searchParams.set("limit","100");const r=await fetch(u,{headers:{"x-api-key":key},cache:"no-store"});if(!r.ok)throw new Error(`SportsGameOdds ${r.status}: ${await r.text()}`);const obj=await r.json(),events=obj.data||obj.events||[],games=[];for(const ev of events){const home=teamAbbr(ev.teams?.home),away=teamAbbr(ev.teams?.away);if(!home||!away)continue;const q=spreadRecords(ev),pp=pairs(q.home,q.away),hs=median(pp.map(x=>x.homeSpread)),as=median(pp.map(x=>x.awaySpread)),valid=hs!==null&&as!==null&&Math.abs(hs+as)<=.26;games.push({eventID:ev.eventID,startTime:ev.startTime,home,away,valid,warning:valid?"":"no valid paired spread data",method:`SportsGameOdds median (${pp.length} books)`,bookDetail:pp.slice(0,6).map(x=>`${x.book}:${away} ${x.awaySpread>0?"+":""}${x.awaySpread}/${home} ${x.homeSpread>0?"+":""}${x.homeSpread}`).join(" | "),homeSpread:valid?hs:null,awaySpread:valid?as:null,pairedBooks:pp.length});}return {games,eventCount:events.length,validCount:games.filter(g=>g.valid).length,source:"SportsGameOdds"};}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store, no-cache, must-revalidate, max-age=0");const ok=process.env.THE_ODDS_API_KEY,sk=process.env.SPORTSGAMEODDS_API_KEY,errors=[];if(ok){try{return res.status(200).json({...await oddsApi(ok),updatedAt:new Date().toISOString()});}catch(e){errors.push(String(e));}}if(sk){try{return res.status(200).json({...await sgo(sk),updatedAt:new Date().toISOString(),fallbackUsed:!!ok,errors});}catch(e){errors.push(String(e));}}return res.status(503).json({success:false,error:"No live odds source available",detail:errors.join(" | ")||"Configure THE_ODDS_API_KEY or SPORTSGAMEODDS_API_KEY."});}
